name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest

    - name: Deploy to Render
      if: success()
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        curl -X POST \
          -H 'Accept: application/json' \
          -H 'Authorization: Bearer rnd_kxWpgfpwq5VZhjHdRGunfXnqInwI' \
          -H 'Content-Type: application/json' \
          --data '{"clearCache": true}' \
          "https://api.render.com/deploy/srv-cpgtn4f109ks73ddjb6g?key=UoHryFy12N4"
