name: 'test my project'
on: [push]
jobs:
 checks:
  runs-on: ubuntu-latest
  steps:
  - name: Begin
    uses: actions/checkout@v3
  - name: Setup Python
    uses: actions/setup-python@v2
  - name: Setup dependencies
    run: pip install -r requirements.txt
  - name: Run tests
    run: python3 tests.py
  - name: Deploy
    run: curl -X GET "https://api.render.com/deploy/srv-cpgtn4f109ks73ddjb6g?key=UoHryFy12N4"
